<?php
$roasts = [
    "{name}, tu itna slow hai, tere screenshots bhi loading lete hain.",
    "{name}, tere jaise logon ki wajah se shampoo par 'do not drink' likhna padta hai.",
    "{name}, tu toh Google ka opposite hai, tujhme kuch bhi useful nahi hai.",
    "{name}, agar bewakoofi Olympic sport hoti, tu gold jeetta har baar.",
    "{name}, tu itna bore hai ki Netflix bhi tujhe skip kar deta.",
    "{name}, teri smile dekh ke toothpaste wale bhi resign de dete.",
    "{name}, tera sense of humor Windows XP jaise outdated hai.",
    "{name}, tu toh WhatsApp ka forwarded message hai — bina kaam ka aur sabko pareshan karta hai.",
    "{name}, tere jaise logon se toh AI bhi seekhne se mana kar deta hai.",
    "{name}, teri baatein sunke lagta hai ki mute button zinda hota toh khud dab jata.",
    "{name}, tu toh YouTube ke unskippable ad jaise hai — annoying aur forced.",
    "{name}, tu jab smart banta hai na, to Wi-Fi bhi disconnect ho jata hai.",
    "{name}, tera logic toh 2G speed se bhi slow hai.",
    "{name}, tu itna confuse karta hai, ki calculator bhi error de deta.",
    "{name}, tere jokes pe sirf walls laugh karti hain — woh bhi stress mein.",
    "{name}, tu zyada hi original hai — no brain, no copy.",
    "{name}, tu itna useless hai ki tere liye Ctrl+Z bhi kaam nahi karta.",
    "{name}, tere ideas toh Windows Vista se bhi bekaar hain.",
    "{name}, tu toh bina charger wale phone jaisa hai — kisi kaam ka nahi.",
    "{name}, tu itna shallow hai ki swimming pool mein bhi doob nahi sakta.",
    "{name}, tu toh pani ka bulb hai — bekaar aur confusing.",
    "{name}, tera IQ room temperature se bhi kam hai.",
    "{name}, tu sochta bhi hai ya bas hawa bharata hai?",
    "{name}, tere jaise logon ke liye 'skip intro' zindagi mein bhi chahiye.",
    "{name}, tu itna thanda hai ki AC tujhe dekh ke heat mode mein chala jata hai.",
    "{name}, tu har conversation ka anti-climax hai.",
    "{name}, tere bina silence bhi entertaining lagta hai.",
    "{name}, tu toh calculator ke 'AC' button jaisa hai — sab kuch reset kar deta bina kaam ka.",
    "{name}, tu itna annoying hai ki alarm bhi tujhe snooze kar deta.",
    "{name}, tere andar itna talent hai jitna desert mein paani.",
    "{name}, tu ek walking cringe compilation hai.",
    "{name}, tu itna fake hai ki Instagram filter bhi tujhe real bolta hai.",
    "{name}, tu toh life ka buffering circle hai — har waqt load le raha hai.",
    "{name}, tere jokes pe log rote hain — haste nahi.",
    "{name}, tu raat ka sapna nahi, dinn ka nightmare hai.",
    "{name}, teri baat sunke plants bhi sukh jaate hain.",
    "{name}, tu toh WhatsApp ke last seen jaisa hai — important lagta hai par kuch kaam ka nahi.",
    "{name}, tu bina battery ka remote hai — bas pada rehta hai.",
    "{name}, tu itna lazy hai ki khaali plate dekh ke bhi thak jaata hai.",
    "{name}, teri speed dekh ke tortoise bhi race jeet jaye.",
    "{name}, tu toh toothpaste ki cap jaisa hai — bas har jagah ghoomta hai, kaam ka nahi.",
    "{name}, teri presence itni useless hai jaise group mein silent member.",
    "{name}, tu itna over smart hai ki bulb ko bhi advice deta hai.",
    "{name}, tu itna low quality hai ki Made in China bhi tujhe accept nahi karega.",
    "{name}, tu zyada hi valuable hai — recycle bin mein.",
    "{name}, tera swag dekh ke road bhi U-turn le leti hai.",
    "{name}, tu toh Wi-Fi ka expired password hai.",
    "{name}, tu itna fake hai ki duplicate pencil tujhe asli samajh le.",
    "{name}, tu itna samajdaar hai jitna mitti mein Wi-Fi.",
    "{name}, tu jab bhi bolta hai, lagta hai mute hi best option hai.",
    "{name}, tu toh shadow ka bhi mood kharab kar deta hai.",
    "{name}, tu sochta kam, bolta zyada hai — noise pollution ka asli source.",
    "{name}, tere sense of fashion pe kapde bhi sharmayein.",
    "{name}, tu na ho toh duniya safe feel kare.",
    "{name}, tu toh loading screen jaisa hai — wait karwa ke kuch nahi deta.",
    "{name}, tu aur tere plans — dono kabhi kaam nahi karte.",
    "{name}, tu WhatsApp forward ka human version hai — boring aur outdated.",
    "{name}, tu itna negative hai ki battery bhi tujhe avoid kare.",
    "{name}, tu video game ka bug hai — sab kuch kharab kar deta hai.",
    "{name}, tu toh Wi-Fi signal ka ek dot hai — bas naam ka.",
    "{name}, tere ideas sirf museum ke laayak hain — purane aur bekaar.",
    "{name}, tu photo ke blur part ka inspiration hai.",
    "{name}, tu bina subtitles ka foreign movie hai — samajh nahi aata.",
    "{name}, tu fake news ka source lagta hai.",
    "{name}, tu Instagram ke fake giveaway jaisa hai.",
    "{name}, tu jab bhi kuch bolta hai, dictionary sharm se band ho jaati hai.",
    "{name}, tu toh calculator se bhi kam useful hai art exam mein.",
    "{name}, tu real life ka April Fool hai.",
    "{name}, tu toh exam ke last question jaisa hai — samajh bhi nahi aata aur marks bhi nahi deta.",
    "{name}, tere jaise logon ko dekh ke zombies bhi bhag jaate hain.",
    "{name}, tu toh soya hua antivirus hai.",
    "{name}, tu ek bejaan meme hai — na funny, na relevant.",
    "{name}, tu toh default ringtone ka bhi downgrade hai.",
    "{name}, tu jab smart banta hai, toh NASA bhi mission cancel kar deta hai.",
    "{name}, tera confidence toh empty folder jaisa hai — bas naam ka.",
    "{name}, tu toh cold drink ke bina gas jaisa hai.",
    "{name}, tu itna fake hai ki plastic tujhe original samjhe.",
    "{name}, tu bad luck ka brand ambassador hai.",
    "{name}, tu toh radio ka broken channel hai — irritating aur nonstop.",
    "{name}, tu itna confused hai ki GPS bhi tujhe ignore karta hai.",
    "{name}, tu Facebook ke friend request ka regret hai.",
    "{name}, tere jokes pe sirf insects haste hain — woh bhi marne ke baad.",
    "{name}, tu exam sheet ka last page hai — blank aur useless.",
    "{name}, tu toh laptop ka stuck key hai.",
    "{name}, tu bas ek background noise hai zindagi mein.",
    "{name}, tu toilet paper ka used side hai — bas use hone ke baad feka gaya.",
    "{name}, tu toh password reset link jaisa hai — kaam ka tab tak jab tak expire na ho.",
    "{name}, tu trailer jaisa exciting hai, lekin content zero.",
    "{name}, tu life ka buffering wheel hai — bas ghoomta rehta hai, kuch karta nahi.",
    "{name}, tu vo hai jo class mein sabse pehle uthta hai, lekin jawab galat deta hai.",
    "{name}, tu chocolate ka empty wrapper hai — bas umeed thi, taste nahi.",
    "{name}, tu calculator ka OFF button hai — sab kuch khatam kar deta hai.",
    "{name}, tu Wi-Fi ka password guess karne jaisa hai — try karte jao, kaam kuch nahi.",
    "{name}, tu ek ghanta lamba ad break hai match ke beech mein.",
    "{name}, tere jaise doston se toh Google Translate better advice deta hai.",
    "{name}, tu keyboard ka stuck key hai — sirf noise karta hai, kaam nahi.",
    "{name}, tu dictionary mein “waste of time” ke saamne photo hona chahiye.",
];
?>
